### ISSUE TITLE
SciPy2019-ModuleNotFound Error notebook

### ISSUE THREAD

**Issue by thedatalass** [econ-ark/DemARK#39] opened 2019-07-13 22:51 UTC
[Lifecycle Model Example](https://github.com/econ-ark/DemARK/blob/master/notebooks/LifecycleModelExample.ipynb)
```
# Initial imports and notebook setup, click arrow to show

import HARK.ConsumptionSaving.ConsIndShockModel as Model        # The consumption-saving micro model
import HARK.SolvingMicroDSOPs.EstimationParameters as Params    # Parameters for the consumer type and the estimation
from HARK.utilities import plotFuncsDer, plotFuncs              # Some tools

import numpy as np
```
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d26969f29899> in <module>
      2 
      3 import HARK.ConsumptionSaving.ConsIndShockModel as Model        # The consumption-saving micro model
----> 4 import HARK.SolvingMicroDSOPs.EstimationParameters as Params    # Parameters for the consumer type and the estimation
      5 from HARK.utilities import plotFuncsDer, plotFuncs              # Some tools
      6 

ModuleNotFoundError: No module named 'HARK.SolvingMicroDSOPs.EstimationParameters'
```
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-0734f7422d0c> in <module>
      1 # Set up default values for CRRA, DiscFac, and simulation variables in the dictionary
----> 2 Params.init_consumer_objects["CRRA"]= 2.00            # Default coefficient of relative risk aversion (rho)
      3 Params.init_consumer_objects["DiscFac"]= 0.97         # Default intertemporal discount factor (beta)
      4 Params.init_consumer_objects["PermGroFacAgg"]= 1.0    # Aggregate permanent income growth factor
      5 Params.init_consumer_objects["aNrmInitMean"]= -10.0   # Mean of log initial assets

NameError: name 'Params' is not defined
```

**Comment by mnwhite** [comment] 2019-07-19 13:45
Have you installed HARK?

pip install econ-ark

DemARK uses the HARK package on your computer.

**Comment by mnwhite** [comment] 2019-07-19 13:57
Ok, I see the problem. The directory structure of SolvingMicroDSOPs changed
but this wasn't updated. The files are now in
HARK.SolvingMicroDSOPs.Calibration

**Comment by shaunagm** [comment] 2019-07-22 12:45
Has anyone submitted a PR to change this reference?  If it's just `HARK.SolvingMicroDSOPs.EstimationParameters` I can do it, but if other things got moved around it's probably better if someone else does it.

**Comment by shaunagm** [comment] 2019-07-22 13:09
Also, out of curiosity, when did this happen, and did we flag it as a breaking change at the time?

**Comment by shaunagm** [comment] 2019-07-22 13:25
Actually, probably the thing to do for nearly all the notebooks for now, except those that need `0.10.1`, is to add a `!pip install econ-ark==0.9.1` at the top of them.  I'll keep trying to find if there's a less cumbersome way to pin different notebooks to different versions of a requirement.

**Comment by shaunagm** [comment] 2019-07-22 13:55
Weirdly, on [mybinder](https://mybinder.org/v2/gh/econ-ark/demark/master) this works by default and changing it to use the new folder structure breaks it.  Which is weird, because AFAIK mybinder uses the version of econ-ark in requirements.txt, which is `0.10.1`, which has the new structure - but mybinder is behaving as if it's using `0.9.1`.  But maybe (probably!) I'm misunderstanding how mybinder.org works.

**Comment by shaunagm** [comment] 2019-07-24 18:19
Okay, I can't reproduce the "mybinder is working and that's weird" issue - it's breaking now as would be expected.  And I don't see any other reference to SolvingMicroDSOPs in any of the other notebooks.  So we just need to make the minor change specified here, which I will handle.

**Comment by llorracc** [comment] 2019-07-24 19:36
dev3 release fixed this problem for my students in Budapest

**Comment by shaunagm** [comment] 2019-07-24 19:40
To confirm, the notebook **`Lifecycle Model Example`** worked fine for your students in Budapest?  Were they running from AlphaCruncher caching mybinder, or something else?  Because I looked at this notebook on mybinder.org not an hour ago and it was broken.

**Comment by llorracc** [comment] 2019-07-24 19:46
We are only using a few notebooks.  But one that uses the USactuarial.txt ("Macro-and-Micro-...") works fine.

**Comment by shaunagm** [comment] 2019-07-24 19:52
This is an issue for a different error, the one you are referring to is #43 and is now closed.

**Comment by MridulS** [comment] 2019-10-31 11:55
tested this notebook, fixed in https://github.com/econ-ark/DemARK/pull/54/

**Closed by MridulS** 2019-10-31 11:55 UTC
Labels: bug, priority:medium
